import os
import base64
from pydantic import BaseModel, Field
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage
from langchain_core.output_parsers import PydanticOutputParser

class CriticEvaluation(BaseModel):
    is_accepted: bool = Field(description="True if the image is high quality and free of glaring anatomical errors. False if it needs regeneration.")
    reason: str = Field(description="Short explanation of why it was accepted or rejected.")

class CriticAgent:
    def __init__(self, temperature=0.1, model_name="gemini-2.5-flash"):
        self.llm = ChatGoogleGenerativeAI(model=model_name, temperature=temperature)
        self.parser = PydanticOutputParser(pydantic_object=CriticEvaluation)
        
    def evaluate_image(self, image_path: str, visual_prompt: str) -> CriticEvaluation:
        if not os.path.exists(image_path):
            return CriticEvaluation(is_accepted=False, reason="Image file not found.")
            
        with open(image_path, "rb") as img_file:
            img_data = base64.b64encode(img_file.read()).decode("utf-8")
            
        sys_prompt = f"""You are a strict Webtoon Editor and Quality Assurance bot. 
I will provide you with an expected visual prompt and an image generated by an AI.
Carefully inspect the image for severe anatomical errors: extra fingers, mangled limbs, 
two heads, or extreme noise. If the image is mostly fine despite minor AI artifacts, accept it.
If it has glaring grotesque errors or completely ignores the subject prompt '{visual_prompt}', reject it.

{self.parser.get_format_instructions()}"""

        message = HumanMessage(
            content=[
                {"type": "text", "text": sys_prompt},
                {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{img_data}"}},
            ]
        )
        
        try:
            response = self.llm.invoke([message])
            return self.parser.invoke(response.content)
        except Exception as e:
            return CriticEvaluation(is_accepted=True, reason=f"Failed to evaluate, accepted by default to avoid halt. Error: {e}")

if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()
    agent = CriticAgent()
    
    # Test with the dummy pipeline image
    test_img = "./output/test_pipeline/test_pipeline_final.png"
    if os.path.exists(test_img):
        print("Evaluating test_pipeline_final.png...")
        res = agent.evaluate_image(test_img, "A girl sitting in a cafe.")
        print(res.model_dump_json(indent=2))
